### ISSUE TITLE
signaling doesn't work on safari

### ISSUE THREAD

**Issue by daisylassie** [pirate/WebRTCChat#2]
hi thanxs for sharing, i tested on safari and the signaling popups (exchanging the offer) don't work.

so is it just a demo for firefox or something we can use on all platforms?

**Comment by pirate** [comment]
Chrome, Firefox, Opera, IE, all support WebRTC, it's only Safari that was lagging behind.

They just released support recently for version 11, so make sure you're up-to-date: https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Safari_11_0/Safari_11_0.html
