### ISSUE TITLE
Unable to connect when running from two different laptops on the same network

### ISSUE THREAD

**Issue by ramanarvind** [pirate/WebRTCChat#4]
[webrtc_internals_dump-host.txt](https://github.com/pirate/WebRTCChat/files/5899945/webrtc_internals_dump-host.txt)
[webrtc_internals_dump-join.txt](https://github.com/pirate/WebRTCChat/files/5899946/webrtc_internals_dump-join.txt)

Thanks for this excellent work. It helped me get an idea on how to connect 2 WebRTC channels without using a server / backend. I am however facing a very basic problem. I am able  to use the JS application when I open 2 browser instances on the same laptop. 

However, surpringly I am unable to to get the JS application to work when I use the applications from 2 different laptops even though they are on the same network. I tried this multiple times and of the many attempts, I was able to get the 2 instances to communicate only once.  I am therefore assuming this is some kind of a timing issue. 

The client joining the conference (not the one hosting the conference) complains that the  "Chat partner disconnected". I am not an expert in WebRTC or JavaScript but I debugged this a little further and found that the client joining the conference receives a "oniceconnectionstatechange" event twice after the offer / answers are exchanged.  It first receives "Disconnected" and eventually "Failed".

I am using chrome Version 88.0.4324.104 (Official Build) (64-bit) and am on Windows 10 OS. The behaviour is same even if I use Edge.

I have attached the chrome://webrtc-internals/ logs. Anything else that might help you help me. I am willing to debug the problem further but am unable to figure out how to take this forward.

**Comment by pirate** [comment]
This project is quite old and was written back when WebRTC was brand-new, and not yet supported my all browsers equally. I suspect it's full of things that have subtly changed or broken as the standard and browser implementations have evolved.

I recommend checking out a different lib if you want a good example of how to get it working, I should probably just archive this repo entirely.

**Comment by ramanarvind** [comment]
Alright.... Thanks so much for the prompt response.
